apps:
  - name: lucent_innovation_practical_task
    restart_delay: 100
    script: app.js
    autorestart: true
    env:
      NODE_ENV: default
    env_dev:
      NODE_ENV: dev
    env_qa:
      NODE_ENV: qa
    env_staging:
      NODE_ENV: staging
    env_production:
      NODE_ENV: production